name: Upload artifact and conditionally upload distribution to GitHub Releases and the JetBrains Marketplace

on: push

jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get version from tag
        id: tag_name
        run: |
          if [ $TAG = true ]; then
            echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
          else
            echo ::set-output name=current_version::Unreleased
          fi
        env:
          TAG: ${{ startsWith(github.ref, 'refs/tags/v') }}
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.1.1
        with:
          validation_level: warn
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Plugin
        env:
          VERSION: ${{ steps.changelog_reader.outputs.version }}
          CHANGE_NOTES: ${{ steps.changelog_reader.outputs.changes }}
        run: ./gradlew buildPlugin
      - name: Get distribution
        run: cp build/distributions/*.zip .
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'Kanagawa Theme Distribution'
          path: '*.zip'
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag_name: ${{ github.ref_name }}
          name: Kanagawa Theme ${{ steps.changelog_reader.outputs.version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          files: "*.zip"
          draft: false
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          VERSION: ${{ steps.changelog_reader.outputs.version }}
          CHANGE_NOTES: ${{ steps.changelog_reader.outputs.changes }}
        if: startsWith(github.ref, 'refs/tags/v')
        run: ./gradlew publishPlugin